### ISSUE TITLE
[3.3.0] High energy comsumer and overheating on IOS

### ISSUE THREAD

**Issue by dev-keishen** [cocos/engine-native#3883]
Dear all

I am using cocos creator 3.3.0. and got an issue that :
Energy consumer is very high and my IOS was overheating so fast(about 10 minutes)

My project is using many spine animations
I tried to reduce draw call and draw call is about 40 now,but overheating is occuring

I don't know how to resolve it

Could you guys help me by show me some tips to fix that?

This is profile in xcode

<img width="1111" alt="Screen Shot 2021-09-12 at 16 01 39" src="https://user-images.githubusercontent.com/78413486/132983139-52d448ae-7d39-4a0e-96c1-94dc3506376f.png">

Thanks you!

**Comment by minggo** [comment]
@dev-keishen could you please provide a test case?

**Comment by dev-keishen** [comment]
@minggo 
we will make a sample for this

Thank for your response

**Comment by dev-keishen** [comment]
[Uploading TestProject01.zip…]()
@minggo :

**Comment by dev-keishen** [comment]
[TestProject01.zip](https://github.com/cocos-creator/engine-native/files/7234240/TestProject01.zip)
@minggo : 
I would like to send you an test example

This is the result after playing around 15 minutes 
![2021-09-27 14 35 13](https://user-images.githubusercontent.com/78413486/134864435-9d69dcc6-76a6-4374-9419-6238999254ff.jpg)

I hope this example could help you find the issue


Thanks

**Comment by minggo** [comment]
Thanks @dev-keishen .

> This is the result after playing around 15 minutes

Did you test with TestProject01.zip?

**Comment by greenmango2204** [comment]
Thanks for your information @minggo.

**Comment by minggo** [comment]
It is my pleasure. And sorry about the issue.

**Comment by dev-keishen** [comment]
@minggo

**Comment by minggo** [comment]
We planned to release it on Dec. 20.

**Comment by dev-keishen** [comment]
@minggo 
Good to hear you
Thanks

**Comment by minggo** [comment]
Preview version is released in forum: https://forum.cocos.org/t/topic/124094. You can download and have a try.
