### ISSUE TITLE
2.4.10 issue of getBatteryLevel on iOS

### ISSUE THREAD

**Issue by sianzain** [cocos/engine-native#4304]
如果ios沒有開啟監控電池
[UIDevice currentDevice].batteryMonitoringEnabled = YES;
取到的 [UIDevice currentDevice].batteryLevel 為 -1

修正代碼如下
`CCDevice-ios`
float Device::getBatteryLevel()
{
    [UIDevice currentDevice].batteryMonitoringEnabled = YES;
    return [UIDevice currentDevice].batteryLevel;
}

**Comment by minggo** [comment]
@mmyduckx please take a look.
@sianzain please use english in future, thanks

**Comment by mmyduckx** [comment]
Verified. Fixed in https://github.com/cocos/engine-native/pull/4305 and thanks for your contribution.
