### ISSUE TITLE
[3.7.0] iOS crash by calling cc::StencilManager::getDepthStencilState() on Batching process

### ISSUE THREAD

**Issue by thinhlv** [cocos/engine-native#4306]
+ Cocos creator version: 3.7.0
+ Build platform: iOS

step preproduce:
1. Build the game with so many complex spine animations on the screen. (EnableBatch = false, CACHE_MODE = SHARED_CACHE, or REALTIME)
3. Run the game on iOS platform
4. For while, the game will be crashed with batching errors.

Please take a look to the attached files

<img width="1747" alt="Screen Shot 2023-02-03 at 16 15 21" src="https://user-images.githubusercontent.com/18746281/216571272-55dba283-b2a2-4243-b99f-f05b137e426f.png">
<img width="1675" alt="Screen Shot 2023-02-03 at 16 42 02" src="https://user-images.githubusercontent.com/18746281/216571281-8b293dcd-2930-4e43-acbb-b70e08f6387e.png">
<img width="1611" alt="Screen Shot 2023-02-03 at 16 15 12" src="https://user-images.githubusercontent.com/18746281/216571218-588592b6-c428-47cd-8358-b9ca1e373064.png">

**Comment by minggo** [comment]
@thinhlv could you please create issues in https://github.com/cocos/cocos-engine as engine native is merged into https://github.com/cocos/cocos-engine since v3.5.

**Comment by thinhlv** [comment]
moved to https://github.com/cocos/cocos-engine/issues/14587
